Repository bitcoin-sv/spv-wallet-go-client, pull requests merged in 2022-03, with the labels that each got.

#11 Add more transports for paymail and xpub
  buxclient.go
  transports/graphql.go
  transports/http.go
  transports/transports.go
Labels: feature, update

#13 Added missing endpoints
  buxclient.go
  buxclient_test.go
  transports/graphql.go
  transports/graphql_test.go
  transports/http.go
  transports/transports.go
Labels: update

#20 Added new metadata update actions
  .golangci.yml
  destinations.go
  transactions.go
  transports/graphql.go
  transports/http.go
  transports/transports.go
  xpubs.go
Labels: feature, update

#21 Fixed graphql return types when updating metadata
  transports/graphql.go
Labels: feature, update

#22 Changed tx_id to id
  transports/config.go
  transports/graphql.go
Labels: hot-fix, update
