Repository bitcoin-sv/spv-wallet-go-client, pull requests merged in 2023-12, with the labels that each got.

#173 fix(BUX-408): admin query requests are failing because of nil reference and invalid http method
  buxclient.go
  transports/http_admin.go
Labels: bug-P3

#166 feat(BUX-190): add keys generation
  examples/graphql/graphql.go
  examples/http/http.go
  examples/keys/keys.go
  examples/new_paymail/new_paymail.go
  examples/register_xpub/register_xpub.go
  xpriv/xpriv.go
Labels: feature, stale

#174 fix(BUX-408): admin get paymail
  transports/http_admin.go
Labels: bug-P3

#176 BUX-430/Remove logs and debug flag
  buxclient.go
  buxclient_test.go
  client_options.go
  examples/graphql/graphql.go
  examples/http/http.go
  examples/http_with_access_key/http_with_access_key.go
  examples/keys/keys.go
  examples/new_paymail/new_paymail.go
  examples/register_xpub/register_xpub.go
  transports/client_options.go
  transports/graphql.go
  transports/graphql_admin.go
  transports/http.go
  transports/http_admin.go
  transports/interface.go
  transports/transports.go
  transports/transports_test.go
Labels: feature
