Repository bitcoin-sv/spv-wallet-go-client, pull requests merged in 2024-08, with the labels that each got.

#260 build(deps): bump github.com/bitcoin-sv/spv-wallet/models from 1.0.0-…
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
Labels: dependencies, chore, tested

#261 ci(SPV-992): use dependabot update groups
  .github/dependabot.yml
Labels: tested

#252 feat(SPV-896): Regression tests v1
  regression_tests/Taskfile.yml
  regression_tests/regression_test.go
  regression_tests/utils.go
Labels: tested

#263 chore(SPV-000): update to spv-wallet's version beta.23
  admin_contacts_test.go
  contacts_test.go
  examples/create_transaction/create_transaction.go
  examples/go.mod
  examples/go.sum
  fixtures/fixtures.go
  go.mod
  go.sum
Labels: tested

#262 feat(SPV-930): AdminGetWebhooks method
  examples/Taskfile.yml
  examples/go.mod
  examples/go.sum
  examples/webhooks/webhooks.go
  go.mod
  go.sum
  http.go
Labels: feature, tested
