Repository bitcoin-sv/spv-wallet-go-client, pull requests merged in 2024-02, with the labels that each got.

#189 BUX-521: inspect errors in methods
  transports/http_admin.go
Labels: bug-P3

#195 chore(BUX-600): rename go-buxclient
  .all-contributorsrc
  .github/CODE_STANDARDS.md
  .github/FUNDING.yml
  .github/IMAGES/go-share-image.png
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  LICENSE
  Makefile
  README.md
  access_keys.go
  access_keys_test.go
  client_options.go
  destinations.go
  destinations_test.go
  examples/http/http.go
  examples/http_with_access_key/http_with_access_key.go
  examples/keys/keys.go
  examples/new_paymail/new_paymail.go
  examples/register_xpub/register_xpub.go
  fixtures/fixtures.go
  go.mod
  go.sum
  paymail_addresses.go
  paymail_addresses_test.go
  transactions.go
  transactions_test.go
  transports/authentication.go
  transports/config.go
  transports/errors.go
  transports/http.go
  transports/http_admin.go
  transports/interface.go
  transports/transports.go
  walletclient.go
  walletclient_test.go
  xpriv/example_test.go
  xpubs.go
  xpubs_test.go
Labels: update, tested

#194 feat(BUX-223): adjust methods
  .github/workflows/run-tests.yml
  examples/new_paymail/new_paymail.go
  examples/register_xpub/register_xpub.go
  paymail_addresses.go
  paymail_addresses_test.go
  transports/http.go
  transports/http_admin.go
  transports/interface.go
  xpubs.go
  xpubs_test.go
Labels: feature
