Repository bitcoin-sv/spv-wallet-go-client, pull requests merged in 2024-01, with the labels that each got.

#178 chore(BUX-000): remove graphql before v1 release of bux toolbox
  buxclient_test.go
  client_options.go
  examples/graphql/graphql.go
  go.mod
  go.sum
  transports/client_options.go
  transports/config.go
  transports/graphql.go
  transports/graphql_admin.go
  transports/graphql_test.go
Labels: update

#179 feat(BUX-498): remove blockheader methods
  transports/http_admin.go
  transports/interface.go
Labels: feature

#180 docs(BUX-442): updates readme and code standards
  .github/CODE_STANDARDS.md
  README.md
Labels: documentation

#177 BUX-434/Change Readme
  README.md
  examples/http/http.go
  examples/register_xpub/register_xpub.go
Labels: feature

#183 feat(BUX-191): add example for generate function
  xpriv/xpriv_generate_example_test.go
Labels: feature

#184 fix(BUX-191): example in documentation is not working
  xpriv/example_test.go
  xpriv/xpriv_generate_example_test.go
Labels: bug-P3

#187 BUX-491: Admin delete paymail
  transports/http_admin.go
Labels: feature
